# Generated by Django 2.0 on 2020-05-16 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarrito', models.AutoField(db_column='idCarrito', primary_key=True, serialize=False)),
                ('total', models.CharField(blank=True, db_column='Total', max_length=45, null=True)),
                ('cantidad_productos', models.IntegerField(blank=True, db_column='Cantidad_productos', null=True)),
                ('timestap', models.DateTimeField(blank=True, db_column='Timestap', null=True)),
            ],
            options={
                'db_table': 'Carrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, db_column='Apellido', max_length=45, null=True)),
                ('contrasena', models.CharField(blank=True, db_column='Contrasena', max_length=45, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=45, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idcompra', models.AutoField(db_column='idCompra', primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=45, null=True)),
                ('precio_delivery', models.CharField(blank=True, db_column='Precio delivery', max_length=45, null=True)),
                ('tipo_direccion', models.CharField(blank=True, db_column='Tipo direccion', max_length=45, null=True)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=45, null=True)),
                ('distrito', models.CharField(blank=True, db_column='Distrito', max_length=45, null=True)),
                ('comprado', models.TextField(blank=True, db_column='Comprado', null=True)),
                ('entregado', models.IntegerField(blank=True, db_column='Entregado', null=True)),
            ],
            options={
                'db_table': 'Compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryTabla',
            fields=[
                ('iddelivery', models.IntegerField(db_column='idDelivery', primary_key=True, serialize=False)),
                ('distrito', models.CharField(blank=True, db_column='Distrito', max_length=45, null=True)),
                ('precio', models.CharField(blank=True, db_column='Precio', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Delivery_tabla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('idpresentacion', models.AutoField(db_column='idPresentacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=1, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'presentacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproductos', models.AutoField(db_column='idProductos', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=400)),
                ('id_interno', models.IntegerField()),
                ('last_update', models.DateTimeField(blank=True, db_column='Last_update', null=True)),
                ('stock', models.CharField(blank=True, db_column='Stock', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarritoHasProducto',
            fields=[
                ('carrito_idcarrito', models.ForeignKey(db_column='Carrito_idCarrito', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mi_botica.Carrito')),
                ('carrito_cliente', models.IntegerField(db_column='Carrito_Cliente')),
                ('cantidad', models.CharField(blank=True, db_column='Cantidad', max_length=45, null=True)),
                ('subtotal', models.CharField(blank=True, db_column='Subtotal', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Carrito_has_Producto',
                'managed': False,
            },
        ),
    ]
