# Generated by Django 2.0 on 2020-05-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_botica', '0002_auto_20200521_0743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carritohasproducto',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='presentacion',
            table='Presentacion',
        ),
    ]
