# Generated by Django 2.0 on 2020-05-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_botica', '0003_auto_20200521_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carritohasproducto',
            options={'managed': True},
        ),
    ]
