# Generated by Django 2.0 on 2020-05-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_botica', '0004_auto_20200521_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='carritohasproducto',
            options={'managed': False},
        ),
    ]
